/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cancela.view;

import cancela.dados.CancelaDAOException;
import cancela.negocio.CancelaFachada;
import cancela.negocio.Ticket;
import cancela.negocio.TicketEvent;
import cancela.negocio.TicketListener;
import cancela.services.Calculo;
import cancela.services.CalculoSimples;
import java.awt.event.ActionEvent;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author italo
 */
public class TicketPagamentoFramev2 extends javax.swing.JFrame implements TicketListener {

    /**
     * Creates new form TicketPagamentoFramev2
     */
    private final CancelaFachada fac;
    private Ticket ticket;
    private Calculo cs;
    
    public TicketPagamentoFramev2(CancelaFachada fachada, Ticket tick) throws CancelaDAOException {
        this.fac = fachada;
        this.ticket = tick;
        this.cs = new CalculoSimples();
        fac.addCadastroListener(this);
        initComponents();
        atualizaTela();
        liberaOption.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        statusPanel = new javax.swing.JPanel();
        codigoTicket = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dataTicket = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        statusTicket = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        precoTicket = new javax.swing.JTextField();
        propositoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pagamentoPanel = new javax.swing.JPanel();
        liberaOption = new javax.swing.JRadioButton();
        gratisOption = new javax.swing.JRadioButton();
        extraviadoOption = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        pagoField = new javax.swing.JTextField();
        liberaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        codigoTicket.setEditable(false);

        jLabel2.setText("Codigo do ticket");

        dataTicket.setEditable(false);

        jLabel3.setText("Data de entrada");

        statusTicket.setEditable(false);

        jLabel4.setText("Status");

        jLabel5.setText("Total a pagar");

        precoTicket.setEditable(false);

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusTicket)
                    .addComponent(dataTicket)
                    .addComponent(codigoTicket)
                    .addComponent(precoTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        jLabel1.setText("Janela que libera o ticket de pagamento");

        javax.swing.GroupLayout propositoPanelLayout = new javax.swing.GroupLayout(propositoPanel);
        propositoPanel.setLayout(propositoPanelLayout);
        propositoPanelLayout.setHorizontalGroup(
            propositoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, propositoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
        );
        propositoPanelLayout.setVerticalGroup(
            propositoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propositoPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(liberaOption);
        liberaOption.setSelected(true);
        liberaOption.setText("Liberar Ticket");
        liberaOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberaOptionActionPerformed(evt);
            }
        });

        buttonGroup1.add(gratisOption);
        gratisOption.setText("Liberar sem pagar");
        gratisOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gratisOptionActionPerformed(evt);
            }
        });

        buttonGroup1.add(extraviadoOption);
        extraviadoOption.setText("Extraviado");
        extraviadoOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraviadoOptionActionPerformed(evt);
            }
        });

        jLabel6.setText("Total pago ");

        pagoField.setEditable(false);

        liberaButton.setText("Liberar");
        liberaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pagamentoPanelLayout = new javax.swing.GroupLayout(pagamentoPanel);
        pagamentoPanel.setLayout(pagamentoPanelLayout);
        pagamentoPanelLayout.setHorizontalGroup(
            pagamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagamentoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pagamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pagamentoPanelLayout.createSequentialGroup()
                        .addComponent(liberaOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gratisOption)
                        .addGap(12, 12, 12)
                        .addComponent(extraviadoOption))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagamentoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagoField)
                        .addGap(78, 78, 78)
                        .addComponent(liberaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pagamentoPanelLayout.setVerticalGroup(
            pagamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagamentoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pagamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liberaOption)
                    .addComponent(gratisOption)
                    .addComponent(extraviadoOption))
                .addGap(18, 18, 18)
                .addGroup(pagamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pagoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liberaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propositoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pagamentoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(propositoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pagamentoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void liberaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberaButtonActionPerformed
        // TODO add your handling code here:
     try {
        if (fac.validaTicket(ticket.getCodigo().getCodigo())) {
            JOptionPane.showMessageDialog(null, "Este ticket já esta liberado!");
            return;   
        }
        else if (liberaOption.isSelected()) {
            fac.liberaTicket(ticket.getCodigo().getCodigo(), Double.valueOf(pagoField.getText()));
        }
        else if (gratisOption.isSelected()) {
            fac.liberaTicket(ticket.getCodigo().getCodigo(), 0.0);
        }
        else if (extraviadoOption.isSelected()) {
            fac.liberaTicketExtraviado(ticket.getCodigo().getCodigo());
        }
    } catch (CancelaDAOException ex) {
        Logger.getLogger(TicketPagamentoFramev2.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_liberaButtonActionPerformed

    private void gratisOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gratisOptionActionPerformed
        // TODO add your handling code here:
        pagoField.setEditable(false);
        pagoField.setText("0.0");
    }//GEN-LAST:event_gratisOptionActionPerformed

    private void extraviadoOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraviadoOptionActionPerformed
        // TODO add your handling code here:
        pagoField.setEditable(false);
        pagoField.setText(String.valueOf(CalculoSimples.precoExtraviado));
    }//GEN-LAST:event_extraviadoOptionActionPerformed

    private void liberaOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberaOptionActionPerformed
        // TODO add your handling code here:
       pagoField.setEditable(true); 
       pagoField.setText(String.valueOf(cs.calculaPreco(this.ticket)));
    }//GEN-LAST:event_liberaOptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField codigoTicket;
    private javax.swing.JTextField dataTicket;
    private javax.swing.JRadioButton extraviadoOption;
    private javax.swing.JRadioButton gratisOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton liberaButton;
    private javax.swing.JRadioButton liberaOption;
    private javax.swing.JPanel pagamentoPanel;
    private javax.swing.JTextField pagoField;
    private javax.swing.JTextField precoTicket;
    private javax.swing.JPanel propositoPanel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextField statusTicket;
    // End of variables declaration//GEN-END:variables

    @Override
    public void elementoAlterado(TicketEvent evt) {
        try {
            this.ticket = fac.getTicketPorCodigo(ticket.getCodigo());
            atualizaTela();
        } catch (CancelaDAOException ex) {
            Logger.getLogger(TicketPagamentoFramev2.class.getName()).log(Level.SEVERE, null, ex);
        }
     }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void atualizaTela() throws CancelaDAOException {
      codigoTicket.setText(ticket.getCodigo().getCodigo());
      dataTicket.setText(String.valueOf(new Timestamp(ticket.getDate().getTimeInMillis())));
      statusTicket.setText(fac.getStatusDescricao(ticket.getStatus()));
      precoTicket.setText(String.valueOf(cs.calculaPreco(ticket)));
    }
}
