/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cancela.view;

import cancela.dados.CancelaDAOException;
import cancela.negocio.CancelaFachada;
import cancela.negocio.CancelaFachadaGerencial;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 12104861
 */
public class TicketMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form TicketMainFrame
     */
    public CancelaFachada fac;
    public TicketMainFrame(CancelaFachada fachada) {
        fac = fachada;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        geraButton = new javax.swing.JButton();
        buscaTicket = new javax.swing.JButton();
        gerenciaisButtons = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho de tecnicas");
        setResizable(false);

        jLabel1.setText("Escolha a opção desejada");

        geraButton.setText("Gera Ticket");
        geraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geraButtonActionPerformed(evt);
            }
        });

        buscaTicket.setText("Busca Ticket");
        buscaTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaTicketActionPerformed(evt);
            }
        });

        gerenciaisButtons.setText("Opções Gerenciais");
        gerenciaisButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciaisButtonsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerenciaisButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(geraButton)
                .addGap(26, 26, 26)
                .addComponent(buscaTicket)
                .addGap(26, 26, 26)
                .addComponent(gerenciaisButtons)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaTicketActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TicketBuscaFrame(fac).setVisible(true);
            }
        });
    }//GEN-LAST:event_buscaTicketActionPerformed

    private void gerenciaisButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciaisButtonsActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new GerencialTicket(new CancelaFachadaGerencial()).setVisible(true);
                } catch (CancelaDAOException ex) {
                    Logger.getLogger(TicketMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_gerenciaisButtonsActionPerformed

    private void geraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geraButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TicketCriadoFrame(fac.adicionaTicket()).setVisible(true);
                } catch (CancelaDAOException ex) {
                    Logger.getLogger(TicketMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_geraButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TicketMainFrame(new CancelaFachada()).setVisible(true);
                } catch (CancelaDAOException ex) {
                    Logger.getLogger(TicketMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscaTicket;
    private javax.swing.JButton geraButton;
    private javax.swing.JButton gerenciaisButtons;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
